-- Adventurers Chronicles - Esquema de base de datos
-- RETO 4: Autenticación de usuarios

CREATE DATABASE IF NOT EXISTS adventurers_chronicles
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE adventurers_chronicles;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Preparada para RETO 5 (guardar progreso). No se usa todavía.
CREATE TABLE IF NOT EXISTS characters (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(20) NOT NULL,
  job VARCHAR(30) NOT NULL DEFAULT 'Novato',
  level INT UNSIGNED NOT NULL DEFAULT 1,
  xp INT UNSIGNED NOT NULL DEFAULT 0,
  hp INT UNSIGNED NOT NULL DEFAULT 100,
  max_hp INT UNSIGNED NOT NULL DEFAULT 100,
  mp INT UNSIGNED NOT NULL DEFAULT 50,
  max_mp INT UNSIGNED NOT NULL DEFAULT 50,
  gold INT UNSIGNED NOT NULL DEFAULT 0,
  pos_x INT NOT NULL DEFAULT 500,
  pos_y INT NOT NULL DEFAULT 500,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
